name: Bug Report

description: File a bug report.

title: "[Bug]: "

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: input
    attributes:
      label: Moment.js code
      placeholder: Type it
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Temporal code
      placeholder: Type it
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false