name: Transformation Bug Report

description: File a bug relating to an incorrect code transformation

title: "[Bug]: "

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: input
    attributes:
      label: Input
      placeholder: The Moment.js code that was passed to the transformer
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Output
      placeholder: The Temporal code that the transformer produced
    validations:
      required: true

  - type: textarea
    id: explanation
    attributes:
      label: Explain why this transformation is incorrect

  - type: textarea
    id: extra
    attributes:
      label: Anything else we should know?

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false